sudo: required
services:
  - docker

before_install: 
  - docker build -t deepak1947/docker-react -f dev.Dockerfile .

script:
  - docker run -e CI=true deepak1947/docker-react npm run test -- --coverage 


