sudo: required
services:
  - docker

before_install: 
  - docker build -t deepak1947/docker-react -f dev.Dockerfile .

script:
  - docker run deepak1947/docker-react npm test 

after_success:
  - docker run deepak1947/docker-react npm run coverage

