version: '3'

services:
  react-frontend:
    restart: "no"
    working_dir: /app
    build: 
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - /devArea/udemy/docker-n-kubernetes/frontend:/app